baseurl = "https://youyan.github.io/"
title = "Black & Light"
author = "David Hamp-Gonsalves"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Black & Light"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Projects"
    url  = ""
[[menu.main]]
    name = "Resume"
    url  = ""

