baseurl = "https://youyan.github.io/"
title = "Black & Light"
author = "youyan"
canonifyurls = true
languagecode = "en"
theme = "Fan Fiction _By 又延"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Black & Light"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Projects"
    url  = ""
[[menu.main]]
  

